config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'list_attendances_by_classroom', to: 'list_attendances_by_classroom#index'
        get 'student_activity', to: 'student_activity#check'
        get 'student_classroom_attendances', to: 'student_classroom_attendances#index'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :recovery_lowest_note
        get :in_recovery
        get :select2_remote
        get :search_autocomplete
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history

    get '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#copy'
    post '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#do_copy'

    resources :knowledge_area_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history

    get '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#copy'
    post '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#do_copy'

    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
        get :fetch_grades
      end
    end

    resources :pedagogical_trackings, only: [:index], concerns: :history do
      collection do
        get :teachers
        get :recalculate
      end
    end

    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'

    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      collection do
        get :by_unity
        get :multi_grade
        get :classroom_grades
      end
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_by_grade_and_unity
        get :search_grouped_by_knowledge_area
        get :by_classroom
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index] do
      collection do
        get :for_school_term_type_recovery
      end
    end
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        get :set_avaliation_setting
        get :set_grades_by_classrooms
        get :set_type_score_for_discipline
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
        get :fetch_classrooms
      end
      member do
        post :exempt_students
        post :undo_exemption
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history do
      collection do
        get :fetch_step
        get :fetch_number_of_decimal_places
      end
    end
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes

app/models/final_recovery_diary_record.rb
class FinalRecoveryDiaryRecord < ApplicationRecord
  include Audit
  include Filterable

  acts_as_copy_target

  audited
  has_associated_audits

  before_destroy :valid_for_destruction?

  belongs_to :recovery_diary_record
  belongs_to :school_calendar

  accepts_nested_attributes_for :recovery_diary_record

  delegate :classroom, :classroom_id, :discipline, :discipline_id, to: :recovery_diary_record

  scope :by_unity_id, lambda { |unity_id| joins(:recovery_diary_record).where(recovery_diary_records: { unity_id: unity_id }) }
  scope :by_teacher_id, lambda { |teacher_id| by_teacher_id_query(teacher_id) }
  scope :by_classroom_id, lambda { |classroom_id| joins(:recovery_diary_record).where(recovery_diary_records: { classroom_id: classroom_id }) }
  scope :by_discipline_id, lambda { |discipline_id| joins(:recovery_diary_record).where(recovery_diary_records: { discipline_id: discipline_id }) }
  scope :by_school_calendar_id, lambda { |school_calendar_id| where(school_calendar_id: school_calendar_id) }
  scope :by_recorded_at, lambda { |recorded_at| joins(:recovery_diary_record).where(recovery_diary_records: { recorded_at: recorded_at }) }
  scope :ordered, -> { joins(:recovery_diary_record).order(RecoveryDiaryRecord.arel_table[:recorded_at].desc) }

  validates :recovery_diary_record, presence: true
  validates :school_calendar, presence: true
  validates :year, presence: true

  validate :uniqueness_of_final_recovery_diary_record
  validate :recorded_at_must_be_in_last_school_calendar_step
  validate :uniqueness_of_recorded_at

  def year
    school_calendar.try(:year)
  end

  private

  def self.by_teacher_id_query(teacher_id)
    joins(
      :recovery_diary_record,
      arel_table.join(TeacherDisciplineClassroom.arel_table, Arel::Nodes::OuterJoin)
        .on(
          TeacherDisciplineClassroom.arel_table[:classroom_id]
            .eq(RecoveryDiaryRecord.arel_table[:classroom_id])
            .and(
              TeacherDisciplineClassroom.arel_table[:discipline_id]
                .eq(RecoveryDiaryRecord.arel_table[:discipline_id])
            )
        )
        .join_sources
      )
      .where(TeacherDisciplineClassroom.arel_table[:teacher_id].eq(teacher_id)
      .and(TeacherDisciplineClassroom.arel_table[:active].eq('t')))
  end

  def uniqueness_of_final_recovery_diary_record
    return unless recovery_diary_record

    relation = FinalRecoveryDiaryRecord.by_classroom_id(recovery_diary_record.classroom_id)
      .by_discipline_id(recovery_diary_record.discipline_id)
      .by_school_calendar_id(school_calendar_id)
    relation = relation.where.not(id: id) if persisted?

    errors.add(:year, :uniqueness_of_final_recovery_diary_record) if relation.any?
  end

  def recorded_at_must_be_in_last_school_calendar_step
    return unless recovery_diary_record && school_calendar

    steps = school_calendar.classrooms.by_classroom_id(recovery_diary_record.classroom_id).first.try(&:classroom_steps)
    steps ||= school_calendar.steps

    unless steps.to_a.last.school_calendar_day_allows_entry?(recovery_diary_record.recorded_at)
      errors.add(:recovery_diary_record, :recorded_at_must_be_in_last_school_calendar_step)
      recovery_diary_record.errors.add(:recorded_at, :recorded_at_must_be_in_last_school_calendar_step)
    end
  end

  def uniqueness_of_recorded_at
    return unless recovery_diary_record

    relation = RecoveryDiaryRecord.find_by(unity_id: recovery_diary_record.unity_id, classroom_id: recovery_diary_record.classroom_id, discipline_id: recovery_diary_record.discipline_id)

    recovery_diary_record.errors.add(:recorded_at, :uniqueness_of_recorded_at) if relation
  end

  def valid_for_destruction?
    @valid_for_destruction if defined?(@valid_for_destruction)
    @valid_for_destruction = begin
      recovery_diary_record.validation_type = :destroy
      recovery_diary_record.valid?
      forbidden_error = I18n.t('errors.messages.not_allowed_to_post_in_date')
      if recovery_diary_record.errors[:recorded_at].include?(forbidden_error)
        errors.add(:base, forbidden_error)
        false
      else
        true
      end
    end
  end
end

app/views/final_recovery_diary_records/_form.html.erb
<%= simple_form_for @final_recovery_diary_record, html: { class: 'smart-form' } do |f| %>
  <%= f.error_notification %>

  <%= f.simple_fields_for :recovery_diary_record, @final_recovery_diary_record.recovery_diary_record.localized do |recovery_diary_record| %>
    <%= f.hidden_field :school_calendar_id %>
    <%= recovery_diary_record.hidden_field :id %>

    <fieldset>
      <div class="row">
        <div class="col col-sm-4">
          <%= recovery_diary_record.association :unity, as: :select2_unity, user: current_user %>
        </div>

        <div class="col col-sm-4">
          <% if current_user.current_role_is_admin_or_employee? %>
            <%= recovery_diary_record.association :classroom, as: :select2_classroom, user: current_user %>
          <% else %>
            <%= recovery_diary_record.association :classroom, as: :select2, elements: @classrooms, user: current_user %>
          <% end %>
        </div>

        <div class="col col-sm-4">
          <% if current_user.current_role_is_admin_or_employee? %>
            <%= recovery_diary_record.association :discipline, as: :select2_discipline, user: current_user,
              classroom_id: @final_recovery_diary_record.recovery_diary_record.classroom_id %>
          <% else %>
            <%= recovery_diary_record.association :discipline, as: :select2, elements: @disciplines, user: current_user,
              classroom_id: @final_recovery_diary_record.recovery_diary_record.classroom_id %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col col-sm-4">
          <%= f.input :year, disabled: true %>
        </div>

        <div class="col col-sm-4">
          <%= recovery_diary_record.input :recorded_at, as: :date %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend><%= t('.students') %></legend>

      <% if recovery_diary_record.object.errors.added? :students, :at_least_one_assigned_student %>
        <div class="alert alert-danger fade in">
          <i class="fa-fw fa fa-times"></i>
          <%= recovery_diary_record.object.errors[:students].first %>
        </div>
      <% end %>

      <table class="table table-striped table-bordered table-condensed records">
        <thead>
          <tr>
            <th><%= RecoveryDiaryRecordStudent.human_attribute_name :student %></th>
            <th width="20%"><%= t('.needed_score') %></th>
            <th width="20%"><%= RecoveryDiaryRecordStudent.human_attribute_name :score %></th>
          </tr>
        </thead>

        <tbody id="recovery-diary-record-students" data-scale="<%= @number_of_decimal_places %>">
          <tr>
            <td class="no_item_found" colspan="3" style="<%= recovery_diary_record.object.students.reject(&:marked_for_destruction?).empty? ? 'display: table-cell;' : 'display: none;' %>" ><%= t('.no_item_found') %></td>
          </tr>

          <%= recovery_diary_record.association :students, collection: recovery_diary_record.object.students.sort_by { |student| student.student.name.upcase } do |student| %>
            <%= render 'student_fields', f: student %>
          <% end %>
        </tbody>
      </table>
    </fieldset>
  <% end %>

  <footer>
    <%= link_to t('views.form.back'), final_recovery_diary_records_path, class: 'btn btn-default' %>

    <% if @final_recovery_diary_record.persisted? %>
      <%= link_to t('views.form.history'),
        history_final_recovery_diary_record_path(@final_recovery_diary_record),
        class: 'btn btn-info' %>
    <% end %>

    <%= f.submit t('views.form.save'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'} %>
  </footer>
<% end %>

app/views/final_recovery_diary_records/_resources.html.erb
<tbody id="resources-tbody">
  <% if @final_recovery_diary_records.empty? %>
    <tr>
      <td class="no_record_found" colspan="5"><%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @final_recovery_diary_records.each do |final_recovery_diary_record| %>
      <tr>
        <td><%= final_recovery_diary_record.recovery_diary_record.unity %></td>
        <td><%= final_recovery_diary_record.recovery_diary_record.classroom %></td>
        <td><%= final_recovery_diary_record.recovery_diary_record.discipline %></td>
        <td><%= l(final_recovery_diary_record.recovery_diary_record.recorded_at) %></td>
        <td class="actions">
          <%= link_to t('views.index.edit'),
                edit_final_recovery_diary_record_path(final_recovery_diary_record),
                class: 'btn btn-success' %>
          <%= link_to t('views.index.delete'),
                final_recovery_diary_record_path(final_recovery_diary_record),
                class: 'btn btn-danger', method: 'delete', data: { confirm: t('views.index.confirm_deletion') } %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/final_recovery_diary_records/_student_fields.html.erb
<tr class="nested-fields <%= f.object.persisted? ? 'existing' : 'dynamic' %>" style="<%= 'display: none;' if f.object.marked_for_destruction? %>">
  <td>
    <% if f.object.persisted? %>
      <%= f.hidden_field :id %>
      <%= f.hidden_field :_destroy %>
    <% end %>

    <%= f.input :student_id, as: :hidden %>
    <span class="multiline"><%= f.object.student.to_s %></span>
  </td>

  <td>
    <span class="needed_score">
      <%= f.object.student.try(:needed_score) unless f.object.marked_for_destruction? %>
    </span>
  </td>

  <td>
    <%= f.input :score, label: false,
          input_html: decimal_input_mask(@number_of_decimal_places) %>
  </td>
</tr>

app/views/final_recovery_diary_records/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/final_recovery_diary_records/history.html.erb
<div class="widget-body">
  <% if resource.recovery_diary_record.all_audits.exists? %>
    <div class="table-responsive">
      <table class="table table-bordered table-only-inner-bordered" id="history">
        <thead>
          <tr>
            <th>Ação</th>
            <th>Alterações</th>
            <th>Autor</th>
            <th>Data</th>
          </tr>
        </thead>
        <tbody>
          <% resource.recovery_diary_record.all_audits.each do |audit| %>
            <%= render 'final_recovery_diary_records/history/history', record: AuditDecorator.new(audit) %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="alert alert-warning alert-dismissable">
      Nenhuma alteração realizada.
    </div>
  <% end %>
</div>

app/views/final_recovery_diary_records/index.html.erb
<div class="widget-body no-padding">
  <%= simple_form_for :search, { url: final_recovery_diary_records_path, method: :get, html: { class: 'filterable_search_form' } } do |f| %>
    <div class="table-responsive">
      <table id="resources" class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"><%= f.input :by_classroom_id, as: :select2, elements: @classrooms, label: false, placeholder: t('.by_classroom_id') %></th>
            <th scope="col"><%= f.input :by_discipline_id, as: :select2, elements: @disciplines, label: false, placeholder: t('.by_discipline_id') %></th>
            <th scope="col"><%= f.input :by_recorded_at, as: :date, label: false, placeholder: t('.by_recorded_at') %></th>
            <th scope="col"><%= link_to t('.new_html'), new_final_recovery_diary_record_path, class: 'btn btn-primary pull-right' %></th>
          </tr>

          <tr>
            <th scope="col"><%= RecoveryDiaryRecord.human_attribute_name :unity %></th>
            <th scope="col"><%= RecoveryDiaryRecord.human_attribute_name :classroom %></th>
            <th scope="col"><%= RecoveryDiaryRecord.human_attribute_name :discipline %>
            <th scope="col" style="width: 10%"><%= RecoveryDiaryRecord.human_attribute_name :recorded_at %></th>
            <th scope="col" style="width: 160px"></th>
          </tr>
        </thead>

        <%= render 'resources' %>

        <tfoot id="paginator" class="remote">
          <td colspan="5">
            <div id="page_entries_info" class="pull-left hidden-xs">
              <%= page_entries_info @final_recovery_diary_records %>
            </div>

            <div class="pull-right">
              <%= paginate @final_recovery_diary_records %>
            </div>
          </td>
        </tfoot>
      </table>
    </div>
  <% end %>
</div>

app/views/final_recovery_diary_records/index.js.erb
$('#resources-tbody').replaceWith('<%= escape_javascript(render('resources')) %>');
$('#paginator .pagination').html('<%= escape_javascript(paginate(@final_recovery_diary_records, remote: true).to_s) %>');
$('#page_entries_info').html('<%= escape_javascript(page_entries_info(@final_recovery_diary_records).to_s) %>');

app/views/final_recovery_diary_records/new.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'views/final_recovery_diary_records/form' %>
<% end %>
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>