config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'list_attendances_by_classroom', to: 'list_attendances_by_classroom#index'
        get 'student_activity', to: 'student_activity#check'
        get 'student_classroom_attendances', to: 'student_classroom_attendances#index'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :recovery_lowest_note
        get :in_recovery
        get :select2_remote
        get :search_autocomplete
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history

    get '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#copy'
    post '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#do_copy'

    resources :knowledge_area_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history

    get '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#copy'
    post '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#do_copy'

    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
        get :fetch_grades
      end
    end

    resources :pedagogical_trackings, only: [:index], concerns: :history do
      collection do
        get :teachers
        get :recalculate
      end
    end

    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'

    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      collection do
        get :by_unity
        get :multi_grade
        get :classroom_grades
      end
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_by_grade_and_unity
        get :search_grouped_by_knowledge_area
        get :by_classroom
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index] do
      collection do
        get :for_school_term_type_recovery
      end
    end
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        get :set_avaliation_setting
        get :set_grades_by_classrooms
        get :set_type_score_for_discipline
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
        get :fetch_classrooms
      end
      member do
        post :exempt_students
        post :undo_exemption
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history do
      collection do
        get :fetch_step
        get :fetch_number_of_decimal_places
      end
    end
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes

app/models/course.rb
class Course < ActiveRecord::Base
  include Discardable

  acts_as_copy_target

  audited

  has_many :grades, dependent: :restrict_with_error

  validates :description, :api_code, presence: true
  validates :api_code, uniqueness: true

  default_scope -> { kept }

  scope :by_unity, ->(unity) { by_unity(unity) }
  scope :ordered, -> { order(arel_table[:description].asc) }

  def self.by_unity(unity)
    joins(grades: [:classrooms]).where(classrooms: { unity_id: unity }).distinct
  end

  def to_s
    description
  end
end

app/helpers/avaliation_helper.rb
module AvaliationHelper
  def show_avaliation_weight
    if @avaliation.test_setting.try(:arithmetic?)
      { class: 'hidden' }
    else
      {}
    end
  end

  def avaliation_data(avaliation)
    @classroom = avaliation.classroom
    @is_multi = @classroom.multi_grade?
    @grades = grades_by_classroom
    @input_value = if @classroom.multi_grade? && avaliation.grade_ids.empty?
                     ''
                   elsif avaliation.grade_ids.present?
                     avaliation.grade_ids.join(',')
                   else
                     @grades.first[:id]
                   end
  end

  def grades_by_classroom
    if @classroom.multi_grade?
      grades_to_select_2(ClassroomsGrade.includes(:grade)
                                        .by_classroom_id(@classroom.id)
                                        .by_score_type(ScoreTypes::NUMERIC)
                                        .order_by_grade_description)
    else
      grades_to_select_2(@classroom.first_classroom_grade)
    end
  end

  def grades_to_select_2(classroom_grades)
    grades = []

    if @classroom.multi_grade?
      classroom_grades.each do |classroom_grade|
        grades << build_grades(classroom_grade.grade)
      end
    else
      grades << build_grades(classroom_grades.grade)
    end

    grades
  end

  def build_grades(grade)
    { id: grade.id, name: grade.description, text: grade.description }
  end
end

app/views/avaliations/_avaliation_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.input :include, as: :boolean, label: false %>
    <%= f.input :classroom_id, as: :hidden %>
  </td>

  <td>
    <%= f.input :classroom, as: :string, label: false, disabled: true,
                input_html: { style:'width: 400px;' }%>
  </td>

  <td>
    <% avaliation_data(f.object) %>
    <%= f.input :grade_ids, as: :select2, elements: @grades.to_json, label: false,
                input_html: { value: @input_value , style:'width: 500px;'},
                readonly: !@is_multi, multiple: @is_multi %>
  </td>

  <td>
    <%= f.input :test_date, as: :date, input_html: { value: f.object.localized.test_date, style:'width: 250px;' },
                label: false%>
  </td>

</tr>

app/views/avaliations/_form.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'views/avaliations/form' %>
<% end %>
<%= simple_form_for @avaliation, html: { class: "smart-form" } do |f| %>
  <%= f.error_notification %>

  <% if @avaliation.errors.any? %>
    <div class="alert alert-danger fade in">
      <i class="fa-fw fa fa-times"></i>
      <% @avaliation.errors.full_messages.each do |message| %>
        <%= message %><br/>
      <% end %>
    </div>
  <% end %>

  <fieldset>
      <div class="row">
        <div class="col col-sm-4">
          <%= f.association :test_setting, as: :select2, elements: @test_settings, hide_empty_element: true,
              input_html: {
                data: { hide_empty_element: true }, value: @test_settings.first.id
              }
          %>
        </div>
      </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :unity, as: :select2_unity, user: current_user %>
      </div>

      <div class="col col-sm-4">
        <% if current_user.current_role_is_admin_or_employee? %>
          <%= f.association :classroom, as: :select2_classroom, user: current_user, record: f.object %>
        <% else %>
          <%= f.association :classroom, as: :select2, elements: @classrooms,
                            user: current_user, record: f.object, readonly: action_name.eql?('edit') %>
        <% end %>
      </div>

      <div class="col col-sm-4">
        <% if current_user.current_role_is_admin_or_employee? %>
          <%= f.association :discipline, as: :select2_discipline, user: current_user, record: f.object,
                            classroom_id: @avaliation.classroom_id %>
        <% else %>
          <%= f.association :discipline, as: :select2, elements: @disciplines, user: current_user, record: f.object,
                             classroom_id: @avaliation.classroom_id, readonly: action_name.eql?('edit')%>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :test_date, as: :date, input_html: { value: f.object.localized.test_date } %>
      </div>

      <div class="col col-sm-4">
        <%= f.input :description, required: true %>
      </div>

      <div class="col col-sm-4">
        <%= f.association :test_setting_test, as: :select2, elements: [] %>
      </div>

      <div class="col col-sm-4">
        <%= f.input :weight, required: true, label_html: show_avaliation_weight,
            input_html: show_avaliation_weight.merge({
               data: { inputmask: "'digits': #{@avaliation.test_setting&.number_of_decimal_places || 0}" }
            })
        %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.association :grades, as: :select2, elements: @grades, multiple: true, required: true,
                          input_html: {
                            value: f.object.grade_ids.join(',').presence || @grades.map{ |g| g.id }.sort.join(','),
                            data: { without_json_parser: true }
                          }%>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-12">
        <%= f.input :observations %>
      </div>
    </div>
  </fieldset>

  <footer>
    <%= link_to(t('views.form.back'), avaliations_path, class: 'btn btn-default') %>

    <%= link_to(t('views.form.history'), history_avaliation_path(@avaliation), class: 'btn btn-info') if @avaliation.persisted? %>

    <%= f.submit(t('views.form.save'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'}) %>
    <%= f.submit(t('.save_and_edit_daily_notes'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'}) %>
  </footer>
<% end %>

app/views/avaliations/_resources.html.erb
<tbody id="resources-tbody">
  <% if @avaliations.empty? %>
    <tr>
      <td class="no_record_found" colspan="7"> <%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @avaliations.each do |avaliation| %>
      <tr>
        <td><%= avaliation.unity %></td>
        <td><%= avaliation.classroom_description %></td>
        <td><%= avaliation.discipline %></td>
        <td><%= l(avaliation.test_date) %></td>
        <td><%= avaliation.current_step %></td>
        <td><%= avaliation %></td>
        <td class="actions">
          <%= link_to t('views.index.edit'), edit_avaliation_path(avaliation), class: 'btn btn-success' %>
          <%= link_to t('views.index.delete'), avaliation_path(avaliation),
                      class: 'btn btn-danger',
                      data: { method: 'delete', confirm: t('views.index.confirm_deletion') } %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/avaliations/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/avaliations/index.html.erb
<div class="widget-body no-padding">
  <%= simple_form_for :filter, { url: avaliations_path, method: :get, html: { class: 'filterable_search_form' } } do |f| %>
    <div class="table-responsive">
      <table class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover" id="resources">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"><%= f.input :by_classroom_id, as: :select2, elements: @classrooms, label: false, placeholder: t('.by_classroom_id') %></th>
            <th scope="col"><%= f.input :by_discipline_id, as: :select2, elements: @disciplines, label: false, placeholder: t('.by_discipline_id') %></th>
            <th scope="col">
              <%= f.input :by_test_date, as: :date, label: false,
                    placeholder: t('.by_test_date') %>
            </th>
            <th scope="col"><%= f.input :by_step_id, as: :select2, elements: @steps, label: false, placeholder: t('.by_step_id') %></th>
            <th scope="col"><%= f.input :by_description, label: false, placeholder: t('.by_description') %></th>
            <th scope="col" class="actions" style="width: 160px;">
              <div class="btn-group">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                  <%= t('.new_html') %> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to t('.new_single'), new_avaliation_path %>
                  </li>
                  <li>
                    <%= link_to t('.new_multiple'), multiple_classrooms_avaliations_path %>
                  </li>
                </ul>
              </div>
            </th>
          </tr>
          <tr>
            <th scope="col"><%= Avaliation.human_attribute_name :unity %></th>
            <th scope="col"><%= Avaliation.human_attribute_name :classroom %></th>
            <th scope="col"><%= Avaliation.human_attribute_name :discipline %></th>
            <th scope="col"><%= Avaliation.human_attribute_name :test_date %></th>
            <th scope="col"><%= Avaliation.human_attribute_name :step %></th>
            <th scope="col"><%= Avaliation.human_attribute_name :description %></th>
            <th scope="col" style="width: 190px"></th>
          </tr>
        </thead>

        <%= render 'resources' %>

        <tfoot id="paginator" class="remote">
          <td colspan="7">
            <div id="page_entries_info" class="pull-left hidden-xs">
              <%= page_entries_info @avaliations %>
            </div>
            <div class="pull-right">
              <%= paginate @avaliations %>
            </div>
          </td>
        </tfoot>
      </table>
    </div>
  <% end %>
</div>

app/views/avaliations/index.js.erb
$('#resources-tbody').replaceWith('<%= escape_javascript(render("resources")) %>');
$('#paginator .pagination').html('<%= escape_javascript(paginate(@avaliations, remote: true).to_s) %>');
$('#page_entries_info').html('<%= escape_javascript(page_entries_info(@avaliations).to_s) %>');

app/views/avaliations/multiple_classrooms.html.erb
<div class="widget-body no-padding">
  <% content_for :js do %>
    <%= javascript_include_tag 'views/avaliations/multiple_classrooms' %>
    <script type="text/javascript">
      window.number_of_classes = <%= @number_of_classes %>;
    </script>
  <% end %>

  <%= simple_form_for @avaliation_multiple_creator_form, url: create_multiple_classrooms_avaliations_path, html: { class: "smart-form" } do |f| %>
    <%= f.error_notification %>
    <%= f.input :school_calendar_id, as: :hidden %>

    <fieldset>
        <div class="row">
          <div class="col col-sm-4">
            <%= f.input :test_setting_id, as: :select2, elements: @test_settings, hide_empty_element: true, input_html: { value: @test_settings.first.id } %>
          </div>
        </div>

      <div class="row">
        <div class="col col-sm-4">
          <%= f.input :unity_id, as: :select2_unity, user: current_user %>
        </div>
        <div class="col col-sm-4">
          <%= f.input :discipline_id, as: :select2, elements: @disciplines %>
        </div>
        <div class="col col-sm-4">
          <%= f.input :test_setting_test_id, as: :select2, elements: [], required: true %>
        </div>
        <div class="col col-sm-4">
          <%= f.input :description, required: true %>
        </div>
      </div>

      <div class="row">


        <div class="col col-sm-4">
          <%= f.input :weight, required: true, input_html: { data: { inputmask: "'digits': 0" } } %>
        </div>
      </div>

      <div class="row">
        <div class="col col-sm-12">
          <%= f.input :observations, as: :text %>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend><%= t('.classrooms') %></legend>

      <% if f.object.errors[:avaliations].present? %>
        <div class="alert alert-danger fade in">
          <i class="fa-fw fa fa-times"></i>
          <%= raw f.object.errors[:avaliations].join("<br/>") %>
        </div>
      <% end %>


      <table class="table table-striped table-bordered table-condensed records">
        <thead>
          <tr>
            <th width="5%">
              <div class="control-group boolean optional">
                <div class="controls input">
                  <input value="0" type="hidden" name="select-all">
                  <label class="checkbox">
                    <input class="boolean optional" type="checkbox" value="1" name="select-all" id="select-all">
                    <i></i>
                  </label>
                </div>
              </div>
            </th>
            <th><%= Avaliation.human_attribute_name(:classroom) %></th>
            <th width="500px"><%= Avaliation.human_attribute_name(:grade) %></th>
            <th width="500px"><%= Avaliation.human_attribute_name(:test_date) %></th>
          </tr>
        </thead>

        <tbody id="avaliations">
          <tr>
            <td class="no_item_found" colspan="4" style="<%= @avaliation_multiple_creator_form.avaliations.empty? ? 'display: table-cell;' : 'display: none;' %>" >
              <%= t('.no_classroom_found') %>
            </td>
          </tr>
          <% if f.object.avaliations.present? %>
            <%= f.simple_fields_for :avaliations, f.object.avaliations do |avaliation| %>
              <%= render 'avaliation_fields', f: avaliation %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </fieldset>

    <footer>
      <%= link_to(t('views.form.back'), avaliations_path, class: 'btn btn-default') %>
      <%= link_to(t('views.form.history'), history_avaliation_path(@avaliation), class: 'btn btn-info') if @avaliation_multiple_creator_form.persisted? %>
      <%= f.submit(t('views.form.save'), class: 'btn btn-primary') %>
    </footer>
  <% end %>
</div>

app/views/avaliations/new.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>