config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'list_attendances_by_classroom', to: 'list_attendances_by_classroom#index'
        get 'student_activity', to: 'student_activity#check'
        get 'student_classroom_attendances', to: 'student_classroom_attendances#index'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :recovery_lowest_note
        get :in_recovery
        get :select2_remote
        get :search_autocomplete
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history

    get '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#copy'
    post '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#do_copy'

    resources :knowledge_area_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history

    get '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#copy'
    post '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#do_copy'

    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
        get :fetch_grades
      end
    end

    resources :pedagogical_trackings, only: [:index], concerns: :history do
      collection do
        get :teachers
        get :recalculate
      end
    end

    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'

    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      collection do
        get :by_unity
        get :multi_grade
        get :classroom_grades
      end
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_by_grade_and_unity
        get :search_grouped_by_knowledge_area
        get :by_classroom
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index] do
      collection do
        get :for_school_term_type_recovery
      end
    end
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        get :set_avaliation_setting
        get :set_grades_by_classrooms
        get :set_type_score_for_discipline
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
        get :fetch_classrooms
      end
      member do
        post :exempt_students
        post :undo_exemption
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history do
      collection do
        get :fetch_step
        get :fetch_number_of_decimal_places
      end
    end
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes

app/controllers/school_calendar_events_controller.rb
class SchoolCalendarEventsController < ApplicationController
  has_scope :page, default: 1
  has_scope :per, default: 10
  respond_to :json, only: [:grades, :classrooms]
  before_action :check_user_unity

  def index
    @school_calendar_events = apply_scopes(school_calendar.events).includes(:grade, :classroom)
                                                                  .ordered

    authorize @school_calendar_events
  end

  def new
    @school_calendar_event = resource
    @school_calendar_event.coverage = params[:coverage]
    @school_calendar_event.periods = Periods.list

    authorize resource
  end

  def create
    resource.assign_attributes resource_params

    authorize resource

    if resource.valid?
      SchoolCalendarEventDays.update_school_days(
        [school_calendar],
        [resource],
        action_name,
        resource.start_date,
        resource.end_date
      )
    end

    if resource.save
      respond_with resource, location: school_calendar_school_calendar_events_path
    else
      clear_invalid_dates
      render :new
    end
  end

  def edit
    @school_calendar_event = resource.localized

    authorize resource
  end

  def update
    resource.assign_attributes resource_params

    authorize resource

    if (dates_changed = resource.start_date_changed? || resource.end_date_changed?)
      old_start_date = resource.start_date_was
      old_end_date = resource.end_date_was
    end

    if resource.save
      if dates_changed
        SchoolCalendarEventDays.update_school_days(
          [school_calendar],
          [resource],
          action_name,
          old_start_date,
          old_end_date
        )
      end
      respond_with resource, location: school_calendar_school_calendar_events_path
    else
      clear_invalid_dates
      render :edit
    end
  end

  def destroy
    authorize resource

    SchoolCalendarEventDays.update_school_days(
      [school_calendar], [resource], action_name
    )

    resource.destroy

    respond_with resource, location: school_calendar_school_calendar_events_path
  end

  def history
    @school_calendar_event = resource

    authorize @school_calendar_event

    respond_with @school_calendar_event
  end

  private

  def courses
    @courses ||= Course.by_unity(@school_calendar.unity.id).ordered || {}
  end
  helper_method :courses

  def grades
    @grades ||= Grade.by_unity(school_calendar.unity.id).ordered
    @grades = @grades.by_course(@school_calendar_event.course_id) if @school_calendar_event.try(:course_id).present?
    @grades
  end
  helper_method :grades

  def classrooms
    @classrooms ||= Classroom.by_unity_and_grade(@school_calendar.unity.id, @school_calendar_event.grade_id).by_year(@school_calendar.year).ordered || {}
  end
  helper_method :classrooms

  def disciplines
    @disciplines ||= Discipline.by_unity_id(@school_calendar.unity.id, current_school_year)
                               .by_classroom(@school_calendar_event.classroom_id)
                               .grouper
                               .ordered || []
  end
  helper_method :disciplines

  def resource
    @school_calendar_event ||= case params[:action]
    when 'new', 'create'
      school_calendar.events.new
    when 'edit', 'update', 'destroy', 'history'
      school_calendar.events.find(params[:id])
    end
  end

  def resource_params
    params.require(:school_calendar_event).permit(
      :coverage, :course_id, :grade_id, :classroom_id, :discipline_id,
      :description, :start_date, :end_date, :event_type, :periods, :legend, :show_in_frequency_record
    )
  end

  def school_calendar
    @school_calendar = SchoolCalendar.find(params[:school_calendar_id])
  end

  def clear_invalid_dates
    start_date = resource_params[:start_date]
    end_date = resource_params[:end_date]

    @school_calendar_event.start_date = '' unless start_date.try(:to_date)
    @school_calendar_event.end_date = '' unless end_date.try(:to_date)
  end

  def check_user_unity
    return if show_all_unities?
    return if current_unity.try(:id) == school_calendar.unity_id

    redirect_to(school_calendars_path, alert: I18n.t('school_calendars.invalid_unity'))
  end

  def show_all_unities?
    @show_all_unities ||= current_user_role.try(:role_administrator?)
  end
  helper_method :show_all_unities?

  def current_user_role
    current_user.current_user_role || current_user.user_roles.first
  end
end

app/views/school_calendar_events/_base_errors.html.erb
<% if f.object.errors[:base].present? %>
  <div class="col col-sm-12">
    <div class="alert alert-danger fade in">
      <button class="close" data-dismiss="alert">
        ×
      </button>
      <i class="fa-fw fa fa-times"></i>
        <%= f.object.errors[:base].first %>
    </div>
  </div>
<% end %>

app/views/school_calendar_events/_classroom_fields.html.erb
<div class="row">
  <div class="col col-sm-4">
    <%= f.input :start_date, as: :date %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :end_date, as: :date%>
  </div>
  <div class="col col-sm-4">
    <%= f.association :course, as: :select2, elements: courses, required: true %>
  </div>

</div>
<div class="row">
  <div class="col col-sm-4">
    <%= f.association :grade, as: :select2, elements: grades, required: true %>
  </div>
  <div class="col col-sm-4">
    <%= f.association :classroom, as: :select2, elements: classrooms, required: true %>
  </div>
  <div class="col col-sm-4">
    <%= f.input :discipline_id, as: :select2, elements: disciplines,
      required: true, empty_element_id: "", empty_element_name: "<option>Todas</option>"  %>
  </div>
</div>

<div class="row">
  <div class="col col-sm-4">
    <%= f.input :description %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :event_type, as: :select2, elements: EventTypes.to_select.to_json %>
  </div>
    <div class="col col-sm-4">
      <%= f.input :periods, as: :select2, multiple: true, elements: PeriodsDecorator.data_for_select2, required: true,
          input_html: { value: f.object.periods.join(','), data: { without_json_parser: true } } %>
    </div>
  <div class="col col-sm-4 hidden" data-event-legend-container>
    <%= f.input :legend, input_html: { maxlength: 1 }, required: true %>
  </div>
  <div class="col col-sm-4 hidden" data-event-checkbox-container>
    <%= f.input :show_in_frequency_record, as: :boolean, label: false, inline_label: true %>
  </div>
</div>

app/views/school_calendar_events/_confirm_delete_event_model.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-delete-school_calendar_event-<%=school_calendar_event.id%>" aria-hidden="true">>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <strong>
          <h4 class="modal-title" style='text-align:left'>Deseja excluir o evento?
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </h4>
        </strong>
      </div>
      <div class="modal-body" style='text-align:left'>
        <strong>
          <h5>Na existência de lançamentos de frequências vinculadas ao evento, estas serão removidas ao excluir o mesmo,
            não sendo possível restaurá-las. Deseja prosseguir?
          </h5>
        </strong>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn new-school-calendar-event-cancel" data-dismiss="modal">Continuar sem excluir</button>
        <%= link_to 'Prosseguir', [@school_calendar, school_calendar_event],
                    class: "btn new-school-calendar-event-button", method: "delete", data: { confirm: "Tem certeza?" } %>
      </div>
    </div>
  </div>
</div>

app/views/school_calendar_events/_course_fields.html.erb
<div class="row">
  <div class="col col-sm-4">
    <%= f.input :start_date, as: :date %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :end_date, as: :date%>
  </div>
  <div class="col col-sm-4">
    <%= f.association :course, as: :select2, elements: courses, required: true %>
  </div>
</div>

<div class="row">
  <div class="col col-sm-4">
    <%= f.input :description %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :event_type, as: :select2, elements: EventTypes.to_select.to_json %>
  </div>
    <div class="col col-sm-4">
      <%= f.input :periods, as: :select2, multiple: true, elements: PeriodsDecorator.data_for_select2, required: true,
          input_html: { value: f.object.periods.join(','), data: { without_json_parser: true } } %>
    </div>
</div>

<div class="row">
  <div class="col col-sm-4 hidden" data-event-legend-container>
    <%= f.input :legend, input_html: { maxlength: 1 }, required: true %>
  </div>
    <div class="col col-sm-4 hidden" data-event-checkbox-container>
    <%= f.input :show_in_frequency_record, as: :boolean, label: false, inline_label: true %>
  </div>
</div>

app/views/school_calendar_events/_form.html.erb
<%= stylesheet_link_tag "school_calendar_events" %>

<%= simple_form_for [@school_calendar, @school_calendar_event], html: { class: "smart-form" } do |f| %>
  <%= f.error_notification %>
  <%= render 'base_errors', f: f %>
  <%= f.input :school_calendar_id, as: :hidden %>
  <%= f.input :unity_id, as: :hidden %>
  <%= f.input :coverage, as: :hidden %>
  <input id="year" type="hidden" name="year" value="<%= @school_calendar.year %>" >

  <fieldset>
    <%case
      when @school_calendar_event.coverage_by_unity?%><%= render 'school_fields', f: f %>
      <% when @school_calendar_event.coverage_by_course?%><%= render 'course_fields', f: f %>
      <% when @school_calendar_event.coverage_by_grade?%><%= render 'grade_fields', f: f %>
      <% when @school_calendar_event.coverage_by_classroom?%><%= render 'classroom_fields', f: f %>
    <%end%>
  </fieldset>

  <footer>
    <%= link_to "Voltar", school_calendar_school_calendar_events_path, class: "btn btn-default" %>

    <% if @school_calendar_event.persisted? %>
      <%= link_to 'Histórico', history_school_calendar_school_calendar_event_path(id: @school_calendar_event, school_calendar: @school_calendar), class: 'btn btn-info' %>
    <% end %>

    <%= link_to "Salvar", nil,  class: "btn btn-primary", id: "new-school-calendar-event-button" %>
    <%= f.submit 'Salvar', class: 'btn btn-primary', id: "submit-school-calendar-event-button", :style => "display: none;"%>

  </footer>
<% end %>

<% content_for :js do %>
  <script type="text/javascript">
    <%= render 'form.js.erb' %>
  </script>
<% end %>

app/views/school_calendar_events/_form.js.erb
$(document).ready(function () {
  function setUpModalOptions() {
    var modalOptions = {
      title: 'Deseja prosseguir com a criação/edição do evento?',
      message: "O tipo de evento 'não permite lançamentos' irá remover as frequências para o(s) dia(s) selecionados, " +
        "caso existam lançamentos, não sendo possível restaurar esses dados. Deseja prosseguir?",
      backdrop: true,
      buttons: {
        cancel: {
          label: 'Continuar sem criar/editar evento',
          className: 'new-school-calendar-event-cancel'
        },
        confirm: {
          label: 'Prosseguir',
          className: 'new-school-calendar-event-button',
          callback: function () {
            $('#submit-school-calendar-event-button').click();
          }
        }
      }
    };
    return modalOptions
  }

  $('#new-school-calendar-event-button').on('click', function (e) {
    e.preventDefault();

    var event_type = $('#school_calendar_event_event_type').val()

    if (['extra_school_without_frequency', 'no_school'].includes(event_type)) {
      bootbox.dialog(setUpModalOptions())
    } else {
      $('#submit-school-calendar-event-button').click();
    }

  });
});

app/views/school_calendar_events/_grade_fields.html.erb
<div class="row">
  <div class="col col-sm-4">
    <%= f.input :start_date, as: :date %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :end_date, as: :date%>
  </div>
  <div class="col col-sm-4">
    <%= f.association :course, as: :select2, elements: courses, required: true %>
  </div>

</div>

<div class="row">
  <div class="col col-sm-4">
    <%= f.association :grade, as: :select2, elements: grades, required: true %>
  </div>
    <div class="col col-sm-4">
      <%= f.input :description %>
    </div>

    <div class="col col-sm-4">
      <%= f.input :event_type, as: :select2, elements: EventTypes.to_select.to_json %>
    </div>
</div>

<div class="row">
    <div class="col col-sm-4">
      <%= f.input :periods, as: :select2, multiple: true, elements: PeriodsDecorator.data_for_select2, required: true,
          input_html: { value: f.object.periods.join(','), data: { without_json_parser: true } } %>
    </div>
  <div class="col col-sm-4 hidden" data-event-legend-container>
    <%= f.input :legend, input_html: { maxlength: 1 }, required: true %>
  </div>
  <div class="col col-sm-4 hidden" data-event-checkbox-container>
    <%= f.input :show_in_frequency_record, as: :boolean, label: false, inline_label: true %>
  </div>
</div>

app/views/school_calendar_events/_resources.html.erb
<tbody id="resources-tbody">
  <% if @school_calendar_events.empty? %>
    <tr>
      <td class="no_record_found" colspan="6"> <%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @school_calendar_events.each do |school_calendar_event| %>
      <tr>
        <td><%= school_calendar_event.duration %></td>
        <td><%= school_calendar_event.description %></td>
        <td><%= school_calendar_event.event_type_humanize %></td>
        <td><%= school_calendar_event.grade %></td>
        <td><%= school_calendar_event.classroom %></td>
        <td class="actions">
          <%= link_to 'Editar', edit_school_calendar_school_calendar_event_path(@school_calendar, school_calendar_event),
            class: "btn btn-success" %>
          <%= link_to '#', class: 'btn btn-danger',
                      data: { toggle: "modal", target: "#modal-delete-school_calendar_event-#{school_calendar_event.id}" } do %>
            Excluir
          <% end %>
          <%= render 'confirm_delete_event_model', :school_calendar_event => school_calendar_event %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/school_calendar_events/_school_fields.html.erb
<div class="row">
  <div class="col col-sm-4">
    <%= f.input :start_date, as: :date %>
  </div>

  <div class="col col-sm-4">
    <%= f.input :end_date, as: :date%>
  </div>
  <div class="col col-sm-4">
    <%= f.input :description %>
  </div>
</div>

<div class="row">

  <div class="col col-sm-4">
    <%= f.input :event_type, as: :select2, elements: EventTypes.to_select.to_json %>
  </div>
    <div class="col col-sm-4">
      <%= f.input :periods, as: :select2, multiple: true, elements: PeriodsDecorator.data_for_select2, required: true,
          input_html: { value: f.object.periods.join(','), data: { without_json_parser: true } } %>
    </div>
  <div class="col col-sm-4 hidden" data-event-legend-container>
    <%= f.input :legend, input_html: { maxlength: 1 }, required: true %>
  </div>
  <div class="col col-sm-4 hidden" data-event-checkbox-container>
    <%= f.input :show_in_frequency_record, as: :boolean, label: false, inline_label: true %>
  </div>
</div>

app/views/school_calendar_events/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/school_calendar_events/index.html.erb
<%= stylesheet_link_tag "school_calendar_events" %>

<div class="widget-body no-padding">
  <%= simple_form_for :filter, { url: school_calendar_school_calendar_events_path, method: :get, html: { class: 'filterable_search_form' } } do |f| %>
  <div class="table-responsive">
    <table class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover" id="resources">
      <thead>
        <tr>
          <th scope="col" style="width: 180px"><%= f.input :by_date, as: :date, label: false, placeholder: t('.by_date') %></th>
          <th scope="col"><%= f.input :by_description, label: false, placeholder: t('.by_description') %></th>
          <th scope="col"><%= f.input :by_type, label: false, as: :select2, elements: EventTypes.to_select.to_json, placeholder: t('.by_type') %></th>
          <th scope="col"><%= f.input :by_grade, as: :select2, elements: grades, label: false, placeholder: t('.by_grade') %></th>
          <th scope="col"><%= f.input :by_classroom, label: false, placeholder: t('.by_classroom') %></th>
          <th scope="col" class="actions" style="width: 160px;">
            <div class="btn-group">
              <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                <%= t('.new_html') %> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <% EventCoverageType.to_a.each do |t, v| %>
                  <li>
                    <%= link_to t, new_school_calendar_school_calendar_event_path(coverage: v) %>
                  </li>
                <% end %>
              </ul>
            </div>
          </th>
        </tr>
        <tr>
          <th scope="col"><%= SchoolCalendarEvent.human_attribute_name :duration %></th>
          <th scope="col"><%= SchoolCalendarEvent.human_attribute_name :description %></th>
          <th scope="col"><%= SchoolCalendarEvent.human_attribute_name :event_type %></th>
          <th scope="col"><%= SchoolCalendarEvent.human_attribute_name :grade %></th>
          <th scope="col"><%= SchoolCalendarEvent.human_attribute_name :classroom %></th>
          <th scope="col"></th>
        </tr>
      </thead>

      <%= render 'resources' %>
      <tfoot id="paginator" class="remote">
        <td colspan="6">
          <div id="page_entries_info" class="pull-left hidden-xs">
            <%= page_entries_info @school_calendar_events %>
          </div>
          <div class="pull-right">
            <%= paginate @school_calendar_events %>
          </div>
        </td>
      </tfoot>
    </table>
  </div>
  <% end %>
</div>

app/views/school_calendar_events/index.js.erb
$('#resources-tbody').replaceWith('<%= escape_javascript(render("resources")) %>');
$('#paginator .pagination').html('<%= escape_javascript(paginate(@school_calendar_events, :remote => true).to_s) %>');
$('#page_entries_info').html('<%= escape_javascript(page_entries_info(@school_calendar_events).to_s) %>');

app/views/school_calendar_events/new.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>