config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'list_attendances_by_classroom', to: 'list_attendances_by_classroom#index'
        get 'student_activity', to: 'student_activity#check'
        get 'student_classroom_attendances', to: 'student_classroom_attendances#index'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :recovery_lowest_note
        get :in_recovery
        get :select2_remote
        get :search_autocomplete
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history

    get '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#copy'
    post '/discipline_teaching_plans/:id/copy', as: :copy_discipline_teaching_plans, to: 'discipline_teaching_plans#do_copy'

    resources :knowledge_area_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history

    get '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#copy'
    post '/knowledge_area_teaching_plans/:id/copy', as: :copy_knowledge_area_teaching_plans, to: 'knowledge_area_teaching_plans#do_copy'

    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
        get :fetch_grades
      end
    end

    resources :pedagogical_trackings, only: [:index], concerns: :history do
      collection do
        get :teachers
        get :recalculate
      end
    end

    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'

    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
        get :print
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      collection do
        get :by_unity
        get :multi_grade
        get :classroom_grades
      end
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_by_grade_and_unity
        get :search_grouped_by_knowledge_area
        get :by_classroom
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index] do
      collection do
        get :for_school_term_type_recovery
      end
    end
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        get :set_avaliation_setting
        get :set_grades_by_classrooms
        get :set_type_score_for_discipline
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
        get :fetch_classrooms
      end
      member do
        post :exempt_students
        post :undo_exemption
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history do
      collection do
        get :fetch_step
        get :fetch_number_of_decimal_places
      end
    end
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes

app/models/learning_objectives_and_skill.rb
class LearningObjectivesAndSkill < ApplicationRecord
  include Audit

  audited
  acts_as_copy_target

  has_enumeration_for :step, with: BnccSteps, create_helpers: true
  has_enumeration_for :field_of_experience, with: BnccExperienceFields, create_helpers: true
  has_enumeration_for :discipline, with: BnccDisciplines, create_helpers: true

  scope :by_code, ->(code) { where('unaccent(code) ILIKE unaccent(?)', "%#{code}%") }
  scope :by_description, ->(description) { where('unaccent(description) ILIKE unaccent(?)', "%#{description}%") }
  scope :by_step, ->(step) { where(step: step) }
  scope :by_discipline, ->(discipline) { where(discipline: discipline) }
  scope :by_field_of_experience, ->(field_of_experience) { where(field_of_experience: field_of_experience) }
  scope :by_grade, ->(grade) { where('?  = ANY(grades)', grade) }
  scope :ordered, -> { order(:code) }

  validates :code, presence: true, uniqueness: true, length: { maximum: 50 }

  validates :description, presence: true
  validates :step, presence: true
  validates :grades, presence: true
end

app/controllers/learning_objectives_and_skills_controller.rb
class LearningObjectivesAndSkillsController < ApplicationController
  has_scope :page, default: 1
  has_scope :per, default: 10

  def index
    @learning_objectives_and_skills = apply_scopes(LearningObjectivesAndSkill.ordered)

    group_children_education = GeneralConfiguration.current.group_children_education

    if group_children_education
      @grades = GroupChildEducations.to_select + ElementaryEducations.to_select[1..-1] +
                AdultAndYouthEducations.to_select[1..-1]
    else
      @grades = ChildEducations.to_select + ElementaryEducations.to_select[1..-1] +
                AdultAndYouthEducations.to_select[1..-1]
    end

    authorize @learning_objectives_and_skills
  end

  def new
    @learning_objectives_and_skill = LearningObjectivesAndSkill.new

    authorize @learning_objectives_and_skill
  end

  def create
    @learning_objectives_and_skill = LearningObjectivesAndSkill.new(learning_objectives_and_skills_params)

    authorize @learning_objectives_and_skill

    if @learning_objectives_and_skill.save
      respond_with @learning_objectives_and_skill, location: learning_objectives_and_skills_path
    else
      @grades = ListGradesByStepBuilder.call(
        @learning_objectives_and_skill.step
      ).to_json
      render :new
    end
  end

  def edit
    @learning_objectives_and_skill = LearningObjectivesAndSkill.find(params[:id])

    @grades = ListGradesByStepBuilder.call(
      @learning_objectives_and_skill.step
    ).to_json

    authorize @learning_objectives_and_skill
  end

  def update
    @learning_objectives_and_skill = LearningObjectivesAndSkill.find(params[:id])

    authorize @learning_objectives_and_skill

    if @learning_objectives_and_skill.update(learning_objectives_and_skills_params)
      respond_with @learning_objectives_and_skill, location: learning_objectives_and_skills_path
    else
      @grades = ListGradesByStepBuilder.call(
        @learning_objectives_and_skill.step
      ).to_json

      render :edit
    end
  end

  def destroy
    @learning_objectives_and_skill = LearningObjectivesAndSkill.find(params[:id])

    authorize @learning_objectives_and_skill

    @learning_objectives_and_skill.destroy

    respond_with(
      @learning_objectives_and_skill,
      location: learning_objectives_and_skills_path,
      alert: @learning_objectives_and_skill.errors.to_a
    )
  end

  def history
    @learning_objectives_and_skill = LearningObjectivesAndSkill.find params[:id]

    authorize @learning_objectives_and_skill

    respond_with @learning_objectives_and_skill
  end

  def contents
    @contents = []

    query = LearningObjectivesAndSkill.ordered
    query = search_query('experience_fields', query) if params[:experience_fields].present?
    query = search_query('disciplines', query) if params[:disciplines].present?
    query = search_query('group_child_schools', query) if params[:group_child_schools].present?

    query.each do |skill|
      @contents << {
        id: skill.id,
        description: "(#{skill.code}) #{skill.description}"
      }
    end

    respond_with(contents: @contents)
  end

  def fetch_grades
    return if params[:step].blank?

    render json: ListGradesByStepBuilder.call(params[:step], false)
  end

  private

  def learning_objectives_and_skills_params
    parameters = params.require(:learning_objectives_and_skill).permit(
      :code,
      :description,
      :step,
      :field_of_experience,
      :discipline,
      :thematic_unit,
      :grades
    )

    return parameters if parameters[:step].blank?

    parameters[:grades] = params.require(:learning_objectives_and_skill)[:grades].split(',')
    parameters
  end

  def grades_query
    <<-SQL
      AND grades @> ARRAY[?]::varchar[])
    SQL
  end

  def disciplines_query
    <<-SQL
      (discipline = ?
    SQL
  end

  def field_of_experience_query
    <<-SQL
      (field_of_experience = ?
    SQL
  end

  def search_query(type, query)
    query_builder = ''
    params_builder = []

    (params[type] || []).each do |index, value|
      query_builder += ' OR ' if index.to_i > 0
      query_builder += type == 'disciplines' ? disciplines_query : field_of_experience_query
      query_builder += value[:grades].present? ? grades_query : ')'
      params_builder << value[:type]
      params_builder << value[:grades] if value[:grades].present?
    end

    query.where(query_builder, *params_builder)
  end
end

app/views/learning_objectives_and_skills/_form.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'views/learning_objectives_and_skills/form' %>
<% end %>

<%= simple_form_for @learning_objectives_and_skill, html: { class: "smart-form" } do |f| %>
  <%= f.error_notification %>

  <fieldset>
    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :code %>
      </div>

      <div class="col col-sm-4">
        <%= f.input :step, as: :select2, elements: BnccSteps.to_select.to_json %>
      </div>
    </div>
    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :grades, as: :select2, elements: @grades, multiple: true,
                    required: true, input_html: { value: f.object.grades.join(','),
                    data: { without_json_parser: true } } %>
      </div>
      <div class="col col-sm-4 only-child-school" style="display: none;">
        <%= f.input :field_of_experience, as: :select2, elements: BnccExperienceFields.to_select.to_json %>
      </div>

      <div class="col col-sm-4 only-elementary-school" style="display: none;">
        <%= f.input :discipline, as: :select2, elements: BnccDisciplines.to_select.to_json %>
      </div>
    </div>
    <div class="row">
      <div class="col col-sm-4 only-elementary-school" style="display: none;">
        <%= f.input :thematic_unit %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-12">
        <%= f.input :description %>
      </div>
    </div>
  </fieldset>

  <footer>
    <%= link_to learning_objectives_and_skills_path, class: "btn btn-default" do %>
      Voltar
    <% end %>

    <% if @learning_objectives_and_skill.persisted? %>
      <%= link_to 'Histórico',
                  history_learning_objectives_and_skill_path(@learning_objectives_and_skill),
                  class: 'btn btn-info'
      %>
    <% end %>

    <button type="submit" class="btn btn-primary">
      Salvar
    </button>
  </footer>
<% end %>

app/views/learning_objectives_and_skills/_resources.html.erb
<tbody id="resources-tbody">
  <% if @learning_objectives_and_skills.empty? %>
    <tr>
      <td class="no_record_found" colspan="5"> <%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @learning_objectives_and_skills.each do |learning_objectives_and_skill| %>
      <tr>
        <td>
          <%= link_to edit_learning_objectives_and_skill_path(learning_objectives_and_skill) do %>
            <%= learning_objectives_and_skill.code %>
          <% end %>
        </td>
        <td><%= learning_objectives_and_skill.description %></td>
        <td><%= learning_objectives_and_skill.step_humanize %></td>
        <td><%= learning_objectives_and_skill.decorator.grades_labels %></td>
        <td class="actions">
          <% if policy(LearningObjectivesAndSkill).update? %>
            <%= link_to 'Editar',
                        edit_learning_objectives_and_skill_path(learning_objectives_and_skill),
                        class: "btn btn-success"
            %>

            <%= link_to 'Excluir',
                        learning_objectives_and_skill_path(learning_objectives_and_skill),
                        class: "btn btn-danger",
                        title: "Excluir #{learning_objectives_and_skill.to_s}",
                        method: "delete",
                        data: { confirm: "Tem certeza?" }
            %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/learning_objectives_and_skills/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/learning_objectives_and_skills/index.html.erb
<div class="widget-body no-padding">
  <div class="table-responsive">
  <%= simple_form_for :filter, {url: learning_objectives_and_skills_path, method: :get,
                                html: {class: 'filterable_search_form'}} do |f| %>
    <table class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover"
           id="resources">
      <thead>
        <tr>
          <th scope="col"><%= f.input :by_code, label: false, placeholder: "Código" %></th>
          <th scope="col"><%= f.input :by_description, label: false, placeholder: "Filtrar objetivo/habilidade" %></th>
          <th scope="col">
            <%= f.input :by_step, as: :select2, label: false, placeholder: "Filtrar etapa",
              elements: BnccSteps.to_select.to_json %>
          </th>
            <th scope="col">
              <%= f.input :by_grade, as: :select2, label: false, placeholder: "Filtrar série",
                elements: @grades.to_json %>
            </th>
          <th scope="col" class="actions">
          </th>
        </tr>
        <tr>
          <th scope="col"><%= LearningObjectivesAndSkill.human_attribute_name :code %></th>
          <th scope="col"><%= LearningObjectivesAndSkill.human_attribute_name :description %></th>
          <th scope="col"><%= LearningObjectivesAndSkill.human_attribute_name :step %></th>
          <th scope="col"><%= LearningObjectivesAndSkill.human_attribute_name :grades %></th>
          <th scope="col" class="actions" style="width: 160px;">
            <% if policy(LearningObjectivesAndSkill).new? %>
                <%= link_to t('.new_html'), new_learning_objectives_and_skill_path, class: "btn btn-primary" %>
            <% end %>
          </th>
        </tr>
      </thead>

      <%= render 'resources' %>
      <tfoot id="paginator" class="remote">
        <td colspan="5">
          <div id="page_entries_info" class="pull-left hidden-xs">
            <%= page_entries_info @learning_objectives_and_skills %>
          </div>
          <div class="pull-right">
            <%= paginate @learning_objectives_and_skills %>
          </div>
        </td>
      </tfoot>
    </table>
  <% end %>
  </div>
</div>

app/views/learning_objectives_and_skills/index.js.erb
$('#resources-tbody')
  .replaceWith('<%= escape_javascript(render("resources")) %>');
$('#paginator .pagination')
  .html('<%= escape_javascript(paginate(@learning_objectives_and_skills, :remote => true).to_s) %>');
$('#page_entries_info')
  .html('<%= escape_javascript(page_entries_info(@learning_objectives_and_skills).to_s) %>');

app/views/learning_objectives_and_skills/new.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>